[build]
  publish = ".next"
  command = "npm run build"
  
  [[plugins]]
    package = "/plugins/test-env-plugin"

  [build.environment]
  NEXT_PUBLIC_FNC_RECYCLING_TOOL_URL = "thequickbrownfoxjumpsovertheextremelylazydogblablablacksheephaveyouanywool"
